apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: openshift-applier
  name: openshift-applier
spec:
  replicas: 1
  selector:
    app: openshift-applier
    deploymentconfig: openshift-applier
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: openshift-applier
        deploymentconfig: openshift-applier
    spec:
      containers:
      - image: :latest
        imagePullPolicy: Always
        name: openshift-applier
        terminationMessagePath: /dev/termination-log
        env:
          - name: GITREPO
            value: 'https://gitlab.com/jonasgovaerts/ocp_namespace-applier.git'
          - name: BRANCH
            value: development
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                key: username 
                name: git-credentials
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: git-credentials
          - name: TIMER
            value: "60"
          - name: DIR
            value: 'test'
        volumeMounts:
          - name: git
            mountPath: "/resources"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: git
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-applier
      from:
        kind: ImageStreamTag
        name: openshift-applier:latest
    type: ImageChange
